baseURL = 'https://bigbangsmugglers.com/'
languageCode = 'en-us'
title = 'Big Bang Smugglers'
theme = 'doks'

# Enable emoji support
enableEmoji = true

# Doks settings
enableGitInfo = false
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'dracula'

[params]
  description = "Forge Your Legacy in the Void. Trade, fight, and dominate in a ruthless universe where every choice shapes your destiny."
  
  [params.doks]
    # Doks theme-specific settings (optional)
    editPage = false
    
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    
  [[menu.main]]
    name = "Guide"
    url = "/guide"
    weight = 20
    
  [[menu.main]]
    name = "Updates"
    url = "/blog"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
