baseURL = 'https://bigbangsmugglers.com/'
languageCode = 'en-us'
title = 'Big Bang Smugglers'
theme = 'blowfish'

# Enable emoji support
enableEmoji = true

[author]
  name = "Big Bang Smugglers Team"

[params]
  description = "Forge Your Legacy in the Void. Trade, fight, and dominate in a ruthless universe where every choice shapes your destiny."
  
[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
    
  [[menu.main]]
    name = "Guide"
    pageRef = "/guide"
    weight = 20
    
  [[menu.main]]
    name = "Updates"
    pageRef = "/blog"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
