baseURL = 'https://bigbangsmugglers.com/'
languageCode = 'en-us'
title = 'Big Bang Smugglers'
theme = 'hextra'

enableEmoji = true
enableRobotsTXT = true
enableGitInfo = false

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[menu]
  [[menu.main]]
    name = "Guide"
    pageRef = "/guide"
    weight = 1
  [[menu.main]]
    name = "Updates"
    pageRef = "/blog"
    weight = 2
  [[menu.footer]]
    name = "Privacy Policy"
    pageRef = "/privacy"
    weight = 1

[params]
  description = "Forge Your Legacy in the Void. Trade, fight, and dominate in a ruthless universe where every choice shapes your destiny."
  
  navbar.displayTitle = true
  navbar.displayLogo = false
  
  page.width = "normal"
  
  footer.displayCopyright = true
  footer.displayPoweredBy = false

[params.search]
  enable = true
  type = "flexsearch"

[outputs]
  home = ["HTML", "RSS", "JSON"]
