baseURL = 'https://bigbangsmugglers.com/'
languageCode = 'en-us'
title = 'Big Bang Smugglers'
theme = 'PaperMod'

enableEmoji = true
enableRobotsTXT = true

[params]
  description = "Forge Your Legacy in the Void. Trade, fight, and dominate in a ruthless universe where every choice shapes your destiny."
  author = "Big Bang Smugglers Team"
  
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false
  
  [params.homeInfoParams]
    Title = "Big Bang Smugglers"
    Content = "Trade, fight, and dominate in a ruthless universe where every choice shapes your destiny."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Guide"
  url = "/guide"
  weight = 20

[[menu.main]]
  name = "Updates"
  url = "/blog"
  weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]
